---
matrix:
  include:
    -
      before_script:
        - "cd java"
      jdk: oraclejdk8
      language: java
      script: "mvn clean package"
    -
      before_script:
        - "cd python2"
        - "pip install --upgrade setuptools"
        - "pip freeze > requirements.txt"
        - "pip install -r requirements.txt"
      cache: pip
      language: python
      python: 2.7
      script:
        - "python -m unittest discover"
    -
      before_script:
        - "cd python3"
        - "pip install --upgrade setuptools"
        - "pip freeze > requirements.txt"
        - "pip install -r requirements.txt"
      language: python
      python: 3.6
      script:
        - "python -m unittest discover"
    -
      before_script:
        - "cd objectivec"
      language: objective-c
      os: osx
      osx_image: xcode8.3
      script:
        - "xcodebuild -workspace project.xcworkspace -scheme AppName -destination 'platform=iOS Simulator,name=iPhone 7,OS=10.3' build test"
    -
      before_script:
        - "cd cpp"
        - "mkdir build"
        - "cd build"
        - "cmake .."
      compiler:
        - gcc
        - clang
      language: cpp
      script: "make && make test"
      -
        before_script:
          - "cd csharp"
        language: csharp
        solution: diff-match-patch.sln
        - dotnet: 1.1.5
          mono: none
          env: DOTNETCORE=1  # optional, can be used to take different code paths in your script
        - mono: latest
        script:
          - ./build.sh
          - ./test.sh
notifications:
  email:
    - m.singh2005@gmail.com
